[package]
name = "suifrs"
version = "0.1.0"
authors = ["RenDaoEr <rendaoer@outlook.com>"]
edition = "2021"
description = "Waiting for a good idea"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
